"""add_views_likes_dislikes_reactions

Revision ID: 9affa31c067c
Revises: 0704864fd521
Create Date: 2026-06-13 14:07:30.296280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9affa31c067c'
down_revision: Union[str, None] = '0704864fd521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reaction', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', 'user_id')
    )
    op.add_column('artifacts', sa.Column('views', sa.Integer(), server_default='0', nullable=False))
    op.add_column('artifacts', sa.Column('likes', sa.Integer(), server_default='0', nullable=False))
    op.add_column('artifacts', sa.Column('dislikes', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artifacts', 'dislikes')
    op.drop_column('artifacts', 'likes')
    op.drop_column('artifacts', 'views')
    op.drop_table('artifact_reactions')
    # ### end Alembic commands ###
