"""Datos semilla del grimorio — portados del design handoff (data.jsx).

Los campos bpm/motif del prototipo eran artefactos del mockup (síntesis WebAudio)
y no se portan: el player de producción reproduce archivos reales.
"""

SCHOOLS = [
    {"id": "invocacion", "name": "Invocación", "glyph": "✶", "hue": "#E6C868",
     "desc": "El arte del cebo y la trampa. Enlaces que prometen una cosa y entregan otra."},
    {"id": "cacofonia", "name": "Cacofonía", "glyph": "♫", "hue": "#9B72CB",
     "desc": "Música y cánticos virales. Melodías que se incrustan en el cráneo y no se marchan."},
    {"id": "ilusionismo", "name": "Ilusionismo", "glyph": "◬", "hue": "#6FB8A6",
     "desc": "La imagen manipulada. Macros, plantillas y retoque alquímico de la realidad."},
    {"id": "adivinacion", "name": "Adivinación", "glyph": "☽", "hue": "#C9A84C",
     "desc": "El verbo escrito. Copypastas, profecías y pergaminos de texto que se replican."},
    {"id": "nigromancia", "name": "Nigromancia", "glyph": "☥", "hue": "#B5552F",
     "desc": "La resurrección de lo muerto. Reliquias del internet antiguo, traídas de vuelta."},
    {"id": "caos", "name": "Caos", "glyph": "☲", "hue": "#D88A4A",
     "desc": "Lo deepfried y lo surreal. Magia que no obedece forma ni razón. Brainrot puro."},
    {"id": "transmutacion", "name": "Transmutación", "glyph": "☿", "hue": "#A0A6CB",
     "desc": "La plantilla que muta. Formatos que se transforman infinitamente de mano en mano."},
    {"id": "cronomancia", "name": "Cronomancia", "glyph": "☼", "hue": "#E0B24A",
     "desc": "Lo que vence al tiempo. Clásicos que no envejecen y se invocan generación tras generación."},
]

ARTIFACTS = [
    {"id": "rickroll", "title": "Never Gonna Give You Up", "type": "hechizo", "school": "invocacion",
     "era": 2007, "glyph": "⚷", "media": "audio",
     "runes": ["bait", "banger", "og", "viral"], "sealed_by": "Archimago Astley",
     "origin": "Canción de Rick Astley (1987), reanimada como conjuro.",
     "desc": "Conjuro de redirección por excelencia. El incauto sigue un enlace creyendo invocar un tesoro y, en su lugar, es transportado al vídeo de esta balada. El hechizo es irrompible: nunca te abandonará, nunca te decepcionará.",
     "links": ["numanuma", "trololo", "coffin"]},
    {"id": "doge", "title": "Doge", "type": "reliquia", "school": "ilusionismo",
     "era": 2013, "glyph": "Ꙫ", "media": "image",
     "runes": ["wholesome", "clásico", "irónico"], "sealed_by": "Maestra Vellum",
     "origin": "Shiba Inu llamado Kabosu, anotado en Comic Sans (proscrita en este grimorio).",
     "desc": "Reliquia canina de poder benévolo. Se manifiesta como un Shiba de mirada suspicaz rodeado de inscripciones internas en lengua quebrada: «much wow», «very magic», «so doge». Engendró su propia moneda alquímica.",
     "links": ["thisisfine", "stonks", "surprisedpika"]},
    {"id": "nyancat", "title": "Nyan Cat", "type": "visión", "school": "caos",
     "era": 2011, "glyph": "❂", "media": "video",
     "runes": ["loop", "banger", "viral"], "sealed_by": "Archimago Pop-Tart",
     "origin": "Felino-galleta surcando el cosmos sobre un arcoíris infinito.",
     "desc": "Visión hipnótica de un gato fundido con repostería que deja una estela de arcoíris a su paso por el vacío. Acompañado de un cántico vocaloide que se repite hasta el fin de los tiempos. Ningún aprendiz ha medido su duración real.",
     "links": ["harlemshake", "crabrave", "keyboardcat"]},
    {"id": "distractedbf", "title": "Distracted Boyfriend", "type": "reliquia", "school": "ilusionismo",
     "era": 2017, "glyph": "◬", "media": "image",
     "runes": ["stock", "plantilla", "clásico"], "sealed_by": "Maestra Vellum",
     "origin": "Fotografía de archivo de un trío de viandantes.",
     "desc": "Sello triádico de la tentación. Un hombre vuelve la cabeza hacia una desconocida mientras su acompañante observa con desaprobación. Cada figura admite ser reetiquetada, convirtiendo la escena en alegoría de cualquier deseo y su consecuencia.",
     "links": ["drake", "stonks", "surprisedpika"]},
    {"id": "shadowwizard", "title": "Shadow Wizard Money Gang", "type": "hechizo", "school": "cacofonia",
     "era": 2022, "glyph": "⁂", "media": "audio",
     "runes": ["brainrot", "banger", "viral"], "sealed_by": "El Cónclave",
     "origin": "Estribillo coreado: «we love casting spells».",
     "desc": "Himno gremial de la cofradía de magos de las sombras. Su letra declara abiertamente la afición de la hermandad a lanzar hechizos. Adoptado como lema no oficial de este propio grimorio. Shadow Wizard Money Gang — somos los magos que lanzan los hechizos.",
     "links": ["megalovania", "rickroll", "coffin"]},
    {"id": "navyseal", "title": "Navy Seal Copypasta", "type": "pergamino", "school": "adivinacion",
     "era": 2010, "glyph": "☿", "media": "text",
     "runes": ["copypasta", "maldito", "irónico"], "sealed_by": "Aprendiz Anónimo",
     "origin": "Diatriba anónima de un guerrero fanfarrón.",
     "desc": "Pergamino de furia copiada. Una amenaza interminable y autoparódica en la que el autor enumera sus credenciales marciales con creciente delirio. Se transcribe palabra por palabra, mutando ligeramente en cada copia como un encantamiento degradado.",
     "links": ["allyourbase", "loss", "thisisfine"]},
    {"id": "coffin", "title": "Coffin Dance · Astronomia", "type": "hechizo", "school": "cacofonia",
     "era": 2020, "glyph": "♄", "media": "audio",
     "runes": ["banger", "viral", "irónico"], "sealed_by": "Los Portadores",
     "origin": "Sepultureros danzantes de Ghana sobre música electrónica.",
     "desc": "Marcha fúnebre transmutada en fiesta. Un grupo de pallbearers eleva el ataúd al ritmo de una melodía house, invocada siempre que algo —o alguien— encuentra su final cómico. La muerte, aquí, baila.",
     "links": ["rickroll", "crabrave", "megalovania"]},
    {"id": "trollface", "title": "Trollface", "type": "reliquia", "school": "nigromancia",
     "era": 2008, "glyph": "⍟", "media": "image",
     "runes": ["og", "clásico", "irónico"], "sealed_by": "Maestra Vellum",
     "origin": "Garabato de sonrisa traviesa, tinta sobre lienzo digital.",
     "desc": "Máscara de la travesura. Rostro de sonrisa torcida que corona los relatos de quien provoca por mero deleite —«problem?». Reliquia fundacional de la era de los cómics de rabia.",
     "links": ["allyourbase", "loss", "keyboardcat"]},
    {"id": "allyourbase", "title": "All Your Base Are Belong To Us", "type": "pergamino", "school": "nigromancia",
     "era": 2000, "glyph": "♅", "media": "text",
     "runes": ["og", "2007", "clásico"], "sealed_by": "Aprendiz Anónimo",
     "origin": "Traducción rota de un videojuego de naves.",
     "desc": "Profecía mal traducida de los primeros días de la red. Surgida de una localización defectuosa, su gramática quebrada se convirtió en cántico universal. «Estás en camino a la destrucción». «No tienes ninguna posibilidad de sobrevivir, hazte el tiempo».",
     "links": ["navyseal", "trololo", "trollface"]},
    {"id": "thisisfine", "title": "This Is Fine", "type": "reliquia", "school": "adivinacion",
     "era": 2013, "glyph": "☲", "media": "image",
     "runes": ["wholesome", "maldito", "reacción"], "sealed_by": "El Cónclave",
     "origin": "Can sentado en una estancia en llamas, taza en mano.",
     "desc": "Sello de la negación serena. Un perro toma su café mientras el fuego consume la habitación a su alrededor y declara que todo está bien. Profecía de toda alma que contempla su propio desastre sin inmutarse.",
     "links": ["surprisedpika", "stonks", "navyseal"]},
    {"id": "surprisedpika", "title": "Surprised Pikachu", "type": "reliquia", "school": "ilusionismo",
     "era": 2018, "glyph": "⚡", "media": "image",
     "runes": ["reacción", "plantilla", "viral"], "sealed_by": "Maestra Vellum",
     "origin": "Fotograma de una bestia eléctrica con la boca abierta.",
     "desc": "Máscara de la sorpresa fingida. Se invoca tras una consecuencia perfectamente previsible, simulando un asombro que nadie debería sentir. La criatura eléctrica encarna a quien actúa y luego se escandaliza del resultado.",
     "links": ["doge", "distractedbf", "stonks"]},
    {"id": "stonks", "title": "Stonks", "type": "reliquia", "school": "transmutacion",
     "era": 2017, "glyph": "⍓", "media": "image",
     "runes": ["irónico", "plantilla", "reacción"], "sealed_by": "El Cónclave",
     "origin": "Maniquí trajeado ante una gráfica ascendente y una palabra mal escrita.",
     "desc": "Sigilo de la economía absurda. Un hombre genérico contempla cifras incomprensibles bajo la inscripción deliberadamente errónea «STONKS». Se sella sobre toda decisión financiera —o vital— manifiestamente ruinosa.",
     "links": ["doge", "thisisfine", "surprisedpika"]},
    {"id": "drake", "title": "Drakeposting", "type": "reliquia", "school": "transmutacion",
     "era": 2015, "glyph": "⌬", "media": "image",
     "runes": ["plantilla", "clásico", "reacción"], "sealed_by": "Maestra Vellum",
     "origin": "Díptico de un bardo que rechaza y aprueba.",
     "desc": "Plantilla del juicio en dos actos. En el panel superior, la figura aparta el rostro con desdén; en el inferior, señala con aprobación. Toda dualidad del mundo puede inscribirse en sus dos celdas.",
     "links": ["distractedbf", "stonks", "amongus"]},
    {"id": "crabrave", "title": "Crab Rave", "type": "hechizo", "school": "cacofonia",
     "era": 2018, "glyph": "♋", "media": "audio",
     "runes": ["banger", "loop", "danza"], "sealed_by": "Los Portadores",
     "origin": "Crustáceos danzantes sobre tropical house.",
     "desc": "Festín de los cangrejos. Una multitud de crustáceos celebra al unísono sobre una melodía radiante, invocada cuando algo se considera motivo de júbilo colectivo. El regocijo tiene pinzas.",
     "links": ["coffin", "nyancat", "harlemshake"]},
    {"id": "megalovania", "title": "Megalovania", "type": "hechizo", "school": "cronomancia",
     "era": 2015, "glyph": "❖", "media": "audio",
     "runes": ["banger", "og", "profundo"], "sealed_by": "El Cónclave",
     "origin": "Tema de combate de poder legendario.",
     "desc": "Cántico de batalla supremo. Sus primeras notas bastan para erizar el ánimo de cualquier aprendiz. Asociado a los enfrentamientos más temibles, se ha vuelto sinónimo de determinación implacable.",
     "links": ["shadowwizard", "coffin", "crabrave"]},
    {"id": "harlemshake", "title": "Harlem Shake", "type": "visión", "school": "caos",
     "era": 2013, "glyph": "☄", "media": "video",
     "runes": ["danza", "viral", "brainrot"], "sealed_by": "Archimago Baauer",
     "origin": "Ritual de transformación súbita al caer el bajo.",
     "desc": "Visión de la metamorfosis instantánea. Una figura solitaria se contonea en calma hasta que, al desplomarse el bajo, toda la estancia estalla en delirio colectivo. Hechizo de transición abrupta entre el orden y el caos.",
     "links": ["nyancat", "crabrave", "amongus"]},
    {"id": "loss", "title": "Loss", "type": "pergamino", "school": "adivinacion",
     "era": 2008, "glyph": "⁝", "media": "text",
     "runes": ["maldito", "plantilla", "profundo"], "sealed_by": "El Cónclave",
     "origin": "Cuatro viñetas de tragedia destiladas a geometría.",
     "desc": "El sello más sutil del grimorio. Una historieta de dolor reducida a su esqueleto: cuatro paneles, una disposición mínima de líneas. Quien aprende a verla la reconoce camuflada en cualquier estructura. | || || |_",
     "links": ["navyseal", "allyourbase", "thisisfine"]},
    {"id": "amongus", "title": "Among Us · sus", "type": "reliquia", "school": "transmutacion",
     "era": 2020, "glyph": "⏃", "media": "image",
     "runes": ["brainrot", "viral", "irónico"], "sealed_by": "La Tripulación",
     "origin": "Tripulante con forma de gota y sospecha encarnada.",
     "desc": "Sigilo de la sospecha. Una figura ovoide acusada de impostora encarna toda desconfianza: «sus». Su silueta se ha incrustado en el subconsciente colectivo hasta colarse en cualquier objeto con vaga forma de gota.",
     "links": ["drake", "harlemshake", "stonks"]},
    {"id": "numanuma", "title": "Numa Numa · Dragostea Din Tei", "type": "hechizo", "school": "nigromancia",
     "era": 2004, "glyph": "♒", "media": "audio",
     "runes": ["og", "banger", "webcam"], "sealed_by": "Archimago Astley",
     "origin": "Joven entusiasta gesticulando ante su webcam sobre pop rumano.",
     "desc": "Cántico de júbilo doméstico. Un mortal solitario, ante el ojo de su cámara, se entrega por completo a una melodía en lengua extranjera. Reliquia fundacional de la era en que cualquiera podía volverse leyenda desde su alcoba.",
     "links": ["rickroll", "trololo", "harlemshake"]},
    {"id": "trololo", "title": "Trololo · Eduard Khil", "type": "hechizo", "school": "nigromancia",
     "era": 2010, "glyph": "♬", "media": "audio",
     "runes": ["og", "clásico", "banger"], "sealed_by": "El Cónclave",
     "origin": "Barítono soviético entonando una melodía sin palabras.",
     "desc": "Conjuro vocalizado sin verbo alguno. Un caballero de sonrisa imperturbable canta «lo-lo-lol» con perfecta solemnidad, transformando la ausencia de letra en su mayor poder. Invocado para burlar a quien busca respuestas que no llegarán.",
     "links": ["numanuma", "rickroll", "allyourbase"]},
    {"id": "keyboardcat", "title": "Keyboard Cat", "type": "visión", "school": "nigromancia",
     "era": 2007, "glyph": "♩", "media": "video",
     "runes": ["og", "loop", "clásico"], "sealed_by": "Maestra Vellum",
     "origin": "Felino enfundado en una camisa, tocando un teclado.",
     "desc": "Visión de despedida. Un gato vestido pulsa las teclas de un órgano con paciencia infinita, invocado para sellar el final cómico de cualquier desgracia ajena: «play him off». La música acompaña a quien tropieza.",
     "links": ["nyancat", "trollface", "harlemshake"]},
]

SPELLS = [
    {"id": "cantos-invocacion", "name": "Cánticos de Invocación", "glyph": "✶", "hue": "#E6C868",
     "desc": "Las melodías que han arrastrado a millones a hacer clic donde no debían.",
     "tracks": ["rickroll", "coffin", "numanuma", "shadowwizard"]},
    {"id": "banger-prohibidos", "name": "Bangers Prohibidos", "glyph": "♫", "hue": "#9B72CB",
     "desc": "Cánticos de batalla que ningún aprendiz puede escuchar sentado.",
     "tracks": ["megalovania", "crabrave", "shadowwizard", "coffin"]},
    {"id": "loops-eternos", "name": "Loops Eternos", "glyph": "❂", "hue": "#6FB8A6",
     "desc": "Bucles que no conocen final. Escúchalos bajo tu propio riesgo.",
     "tracks": ["nyancat", "crabrave", "harlemshake"]},
]
